A	.gitignore
A	.oxlintrc.json
A	README.md
M	day1.js
M	demoimport.js
A	index.html
A	package-lock.json
A	package.json
A	public/favicon.svg
A	public/icons.svg
A	src/App.css
A	src/App.jsx
A	src/assets/hero.png
A	src/assets/react.svg
A	src/assets/vite.svg
A	src/index.css
A	src/main.jsx
A	vite.config.js
